alpha: !!python/object/apply:numpy._core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  MzMzMzMz6z8=
initial_temperature: !!python/object/apply:numpy._core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  ZAAAAAAAAAA=
iterations_per_temp: !!python/object/apply:numpy._core.multiarray.scalar
- *id001
- !!binary |
  MgAAAAAAAAA=
tabu_tenure: !!python/object/apply:numpy._core.multiarray.scalar
- *id001
- !!binary |
  BQAAAAAAAAA=
